import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('http://localhost:3000/');
  await page.getByRole('link', { name: 'Login' }).click();
  await page.getByRole('textbox', { name: 'Enter Your Email' }).fill('test@admin.com');
  await page.getByRole('textbox', { name: 'Enter Your Password' }).fill('test@admin.com');
  await page.getByRole('button', { name: 'LOGIN' }).click();
  await expect(page.locator('h1')).toContainText('All Products');
  await page.goto('http://localhost:3000/dashboard/admin/orders');
  await page.getByText('Not Process').click();
  await page.getByText('Processing').nth(1).click();
  await page.getByRole('button', { name: 'Test' }).click();
  await page.getByRole('link', { name: 'Logout' }).click();
  await page.getByRole('textbox', { name: 'Enter Your Email' }).fill('cs4218@test.com');
  await page.getByRole('textbox', { name: 'Enter Your Password' }).fill('cs4218@test.com');
  await page.getByRole('button', { name: 'LOGIN' }).click();
  await expect(page.locator('h1')).toContainText('All Products');
  await page.goto('http://localhost:3000/dashboard/user/orders');
  await expect(page.locator('tbody')).toContainText('Processing');
  await page.getByRole('button', { name: 'CS 4218 Test Account' }).click();
  await page.getByRole('link', { name: 'Logout' }).click();
  await page.getByRole('textbox', { name: 'Enter Your Email' }).fill('test@admin.com');
  await page.getByRole('textbox', { name: 'Enter Your Password' }).fill('test@admin.com');
  await page.getByRole('button', { name: 'LOGIN' }).click();
  await expect(page.locator('h1')).toContainText('All Products');
  await page.goto('http://localhost:3000/dashboard/admin/orders');
  await page.getByText('Processing').click();
  await page.getByText('Not Process').nth(1).click();
  await page.getByRole('button', { name: 'Test' }).click();
  await page.getByRole('link', { name: 'Logout' }).click();
  await page.getByRole('textbox', { name: 'Enter Your Email' }).fill('cs4218@test.com');
  await page.getByRole('textbox', { name: 'Enter Your Password' }).fill('cs4218@test.com');
  await page.getByRole('button', { name: 'LOGIN' }).click();
  await expect(page.locator('h1')).toContainText('All Products');
  await page.goto('http://localhost:3000/dashboard/user/orders');
  await expect(page.locator('tbody')).toContainText('Not Process');
});
