import { test, expect } from '@playwright/test';

test.beforeEach(async ({ page }) => {
  await page.goto('http://localhost:3000/');
  await page.evaluate(() => localStorage.clear());  // To ensure auth state is cleared
  await page.getByRole('link', { name: 'Login' }).click();
})

// Precondition: User has already been registered in the database
const testUser = {
    email: 'testuser@vault.com',
    password: 'test',
}

test('has title', async ({ page }) => {
  await expect(page).toHaveTitle(/Login - Ecommerce App/);
});

test('should have login form', async ({ page }) => {
  await expect(page.getByRole('heading', { name: 'LOGIN FORM' })).toBeVisible();
  await expect(page.getByRole('textbox', { name: 'Enter Your Email' })).toBeVisible();
  await expect(page.getByRole('textbox', { name: 'Enter Your Password' })).toBeVisible();
  await expect(page.getByRole('button', { name: 'Forgot Password' })).toBeVisible();
  await expect(page.getByRole('button', { name: 'LOGIN' })).toBeVisible();

});

test('should allow me to login', async ({ page }) => {
  await page.getByRole('textbox', { name: 'Enter Your Email' }).click();
  await page.getByRole('textbox', { name: 'Enter Your Email' }).fill(testUser.email);
  await page.getByRole('textbox', { name: 'Enter Your Email' }).press('Tab');
  await page.getByRole('textbox', { name: 'Enter Your Password' }).fill(testUser.password);
  await page.getByRole('button', { name: 'LOGIN' }).click();
  
  // Show success message
  await expect(page.getByText('login successfully')).toBeVisible();

  // auth is set in localStorage
  // code generated by AI
  const authData = await page.evaluate(() => localStorage.getItem('auth'));
  expect(authData).not.toBeNull();

  const parsed = JSON.parse(authData);
  expect(parsed).toHaveProperty('token');
  expect(parsed).toHaveProperty('user');
  expect(parsed.user.email).toBe(testUser.email);
  
  // Redirect to homepage (default) after successful login 
  await expect(page).toHaveURL('http://localhost:3000/');
});

test('should not allow login with wrong credentials', async ({ page }) => {
  await page.getByRole('textbox', { name: 'Enter Your Email' }).click();
  await page.getByRole('textbox', { name: 'Enter Your Email' }).fill(testUser.email);
  await page.getByRole('textbox', { name: 'Enter Your Email' }).press('Tab');
  
  // Fill in wrong password
  await page.getByRole('textbox', { name: 'Enter Your Password' }).fill('wrong password');
  await page.getByRole('button', { name: 'LOGIN' }).click();
  
  // Show failure message
  await expect(page.getByText('Invalid email or password')).toBeVisible();
});

test('should redirect user to previous state after login', async ({ page }) => {
  // Set up previous state (cart page) before login
  await page.getByRole('link', { name: 'Cart' }).click();
  await page.getByRole('button', { name: 'Please Login to checkout' }).click();

  // User redirected to login after successful login 
  await expect(page).toHaveURL('http://localhost:3000/login');

  await page.getByRole('textbox', { name: 'Enter Your Email' }).click();
  await page.getByRole('textbox', { name: 'Enter Your Email' }).fill(testUser.email);
  await page.getByRole('textbox', { name: 'Enter Your Email' }).press('Tab');
  await page.getByRole('textbox', { name: 'Enter Your Password' }).fill(testUser.password);
  await page.getByRole('button', { name: 'LOGIN' }).click();
  
  // Show success message
  await expect(page.getByText('login successfully')).toBeVisible();

  // auth is set in localStorage
  // code generated by AI
  const authData = await page.evaluate(() => localStorage.getItem('auth'));
  expect(authData).not.toBeNull();

  const parsed = JSON.parse(authData);
  expect(parsed).toHaveProperty('token');
  expect(parsed).toHaveProperty('user');
  expect(parsed.user.email).toBe(testUser.email);
  
  // Redirect to previous state (cart page) after successful login
  await expect(page).toHaveURL('http://localhost:3000/cart');
});

test('forgot password', async ({ page }) => {
  await page.getByRole('button', { name: 'Forgot Password' }).click();

  // Navigate to forgot password page
  await expect(page).toHaveURL('http://localhost:3000/forgot-password');
});