# SonarQube server settings
sonar.host.url=http://localhost:9000
sonar.token=squ_8a3fecb4bf3246a3a74e09788068a8fa87fd5b91

# Project identification
sonar.projectKey=econ
sonar.projectName=econ
sonar.projectVersion=1.0

# Analysis settings
sonar.sources=client,config,controllers,helpers,middlewares,models
sonar.tests=client,config,controllers,helpers,middlewares,models,__tests__
sonar.test.inclusions=**/*.test.js
